# https://docs.docker.com/compose/django/
version: '3'
# Each service is defined in the file. 
services:
  # Mysql is an object relational database system. Will be
  # the main database for web application.
  # Read more: https://www.mysql.com/
  db_mysql:
    container_name: mysql_django_orm
    image: mysql:5.7.28
    volumes:
      - "./data:/var/lib/mysql"
    ports:
      - 3307:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
  web_django:
    image: django-orm-example
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8001:8000"
    depends_on:
      - db_mysql