# Generated by Django 4.0.2 on 2022-02-11 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Film',
            fields=[
                ('film_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=60)),
                ('description', models.TextField(max_length=1024)),
                ('length', models.IntegerField()),
                ('release_date', models.DateField()),
            ],
        ),
    ]
