# Generated by Django 4.0.2 on 2022-02-11 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sakila', '0002_actor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='actor',
            old_name='release_date',
            new_name='last_modified',
        ),
    ]
