# Generated by Django 4.0.2 on 2022-02-11 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sakila', '0003_rename_release_date_actor_last_modified'),
    ]

    operations = [
        migrations.AddField(
            model_name='actor',
            name='films',
            field=models.ManyToManyField(to='sakila.Film'),
        ),
    ]
